---
label: project
hide_body: false
is_partial: false
fields:
- type: text
  name: title
  label: Title
  default: Project
- name: sub_heading
  label: Sub Heading
  type: text
  hidden: false
  default: New Project
- name: banner_image
  label: Banner Image
  type: file
  description: Dimensions work best at 1200 pixels by 400 pixels
  hidden: false
  default: "/uploads/2018/02/17/building3.jpg"
- name: tags
  label: Tags
  type: tag_list
  hidden: false
  default: []
- name: slug
  label: Slug
  type: text
  hidden: false
  default: Photo
- type: boolean
  default: false
- type: color
  config:
    color_format: Hex
  label: Color
  name: color
  description: Choose your color..
  default: "#50E3C2"
